// SPDX-License-Identifier: MIT
//
// @ruflo/kernel runtime resolver. Per ADR-002a, the kernel ships as Rust
// source compiled to wasm + per-platform NAPI-RS for speed. BUT neither of
// those is guaranteed to be present in a plain `npm install` (the wasm pkg/
// is built by a separate CI job; the NAPI platform packages are optional).
// Without a fallback, `loadKernel()` threw ERR_MODULE_NOT_FOUND and every
// generated harness was dead on arrival. This module therefore ALWAYS has a
// third backend: a dependency-free pure-JS implementation. native > wasm > js,
// but js is the floor — the kernel is always loadable. (ADR-002a §fallback.)

import { createRequire } from 'node:module';

export type { McpServerSpec, ToolSpec, AgentSpec, HookSpec, HarnessSpec, HostAdapter } from './types.js';

export interface KernelInfo {
  version: string;
  git_sha: string;
  target: string;
}

interface KernelBackend {
  kernelInfo(): KernelInfo;
  mcpValidate(specJson: string): string | null;
  version(): string;
  backend: 'native' | 'wasm' | 'js';
}

let _cached: KernelBackend | null = null;

async function loadNative(): Promise<KernelBackend | null> {
  try {
    const plat = `${process.platform}-${process.arch}`;
    const map: Record<string, string> = {
      'darwin-arm64': '@ruflo/kernel-darwin-arm64',
      'darwin-x64': '@ruflo/kernel-darwin-x64',
      'linux-x64': '@ruflo/kernel-linux-x64-gnu',
      'linux-arm64': '@ruflo/kernel-linux-arm64-gnu',
      'win32-x64': '@ruflo/kernel-win32-x64-msvc',
    };
    const pkg = map[plat];
    if (!pkg) return null;
    const mod: any = await import(pkg);
    return {
      kernelInfo: () => mod.kernelInfo(),
      mcpValidate: (s: string) => mod.mcpValidate(s) ?? null,
      version: () => mod.version(),
      backend: 'native',
    };
  } catch {
    return null;
  }
}

async function loadWasm(): Promise<KernelBackend | null> {
  try {
    // @ts-ignore — generated by `wasm-pack build` into ../pkg/, absent during
    // a TS-only build (the WASM CI job builds it separately). A miss is
    // non-fatal: we fall through to the pure-JS backend below.
    const mod: any = await import('../pkg/ruflo_kernel_wasm.js');
    if (typeof mod.default === 'function') {
      await mod.default();
    }
    return {
      kernelInfo: () => mod.kernelInfo(),
      mcpValidate: (s: string) => mod.mcpValidate(s) ?? null,
      version: () => mod.version(),
      backend: 'wasm',
    };
  } catch {
    return null;
  }
}

/**
 * The kernel's own version, read from its package.json. Cached. Falls back to
 * '0.0.0' only if the package.json is somehow unreadable (never expected).
 */
let _version: string | null = null;
function kernelVersion(): string {
  if (_version) return _version;
  try {
    const require = createRequire(import.meta.url);
    // dist/index.js → ../package.json
    _version = (require('../package.json') as { version?: string }).version ?? '0.0.0';
  } catch {
    _version = '0.0.0';
  }
  return _version;
}

/**
 * Pure-JS kernel backend — zero native/wasm dependencies, always available.
 * It reimplements the load-bearing kernel surface (kernelInfo / version /
 * mcpValidate) in TypeScript so a harness installed from npm works with no
 * compiled artifacts. The validation rules mirror crates/kernel/src/mcp.rs
 * exactly (server name non-empty; command XOR url) so behaviour is identical
 * whether the native, wasm, or js backend answers.
 */
function loadJs(): KernelBackend {
  return {
    kernelInfo: () => ({
      version: kernelVersion(),
      git_sha: 'js',
      target: `${process.platform}-${process.arch}`,
    }),
    version: () => kernelVersion(),
    mcpValidate: (specJson: string): string | null => {
      let spec: { name?: unknown; command?: unknown; url?: unknown };
      try {
        spec = JSON.parse(specJson);
      } catch (e) {
        // Mirror the NAPI binding, which throws on unparseable spec JSON.
        throw new Error(`invalid spec json: ${(e as Error).message}`);
      }
      // Rules, byte-for-byte from crates/kernel/src/mcp.rs::validate.
      if (typeof spec.name !== 'string' || spec.name.length === 0) {
        return 'server name is empty';
      }
      const hasCommand = Array.isArray(spec.command) && spec.command.length > 0;
      const hasUrl = typeof spec.url === 'string' && spec.url.length > 0;
      if (hasCommand && hasUrl) return 'command and url are mutually exclusive';
      if (!hasCommand && !hasUrl) return 'either command or url must be set';
      return null;
    },
    backend: 'js',
  };
}

/**
 * Load the kernel. native > wasm > pure-JS. The JS backend is the floor, so
 * this never rejects with a missing-module error. Cached.
 */
export async function loadKernel(): Promise<KernelBackend> {
  if (_cached) return _cached;
  const native = await loadNative();
  _cached = native ?? (await loadWasm()) ?? loadJs();
  return _cached;
}
